
// Import các types
import { SkillCategory, ExperienceType } from '../types';

export const SkillsInfoByLocale: Record<'vi' | 'en', SkillCategory[]> = {
  vi: [
  {
    title: 'Frontend',
    skills: [
      { name: 'HTML', logo: '/tech_logo/html.png' },
      { name: 'CSS', logo: '/tech_logo/css.png' },
      { name: 'SASS', logo: '/tech_logo/sass.png' },
      { name: 'JavaScript', logo: '/tech_logo/javascript.png' },
      { name: 'React JS', logo: '/tech_logo/react.png' },
      { name: 'Redux', logo: '/tech_logo/redux.png' },
      { name: 'Next JS', logo: '/tech_logo/nextjs.png' },
      { name: 'Tailwind CSS', logo: '/tech_logo/tailwindcss.png' },
      { name: 'GSAP', logo: '/tech_logo/gsap.png' },
      { name: 'Material UI', logo: '/tech_logo/materialui.png' },
      { name: 'Bootstrap', logo: '/tech_logo/bootstrap.png' },
    ],
  },
  {
    title: 'Backend',
    skills: [
      { name: 'Springboot', logo: '/tech_logo/springboot.png' },
      { name: 'Node JS', logo: '/tech_logo/nodejs.png' },
      { name: 'Express JS', logo: '/tech_logo/express.png' },
      { name: 'Nest JS', logo: '/tech_logo/nest.png' },
      { name: 'MySQL', logo: '/tech_logo/mysql.png' },
      { name: 'MongoDB', logo: '/tech_logo/mongodb.png' },
      { name: 'PostgreSQL', logo: '/tech_logo/postgre.png' },
      { name: 'SQL', logo: '/tech_logo/sql.png' },
      { name: 'Firebase', logo: '/tech_logo/firebase.png' },
    ],
  },
  {
    title: 'Ngôn ngữ',
    skills: [
      { name: 'C', logo: '/tech_logo/c.png' },
      { name: 'C++', logo: '/tech_logo/cpp.png' },
      { name: 'Java', logo: '/tech_logo/java.png' },
      { name: 'Python', logo: '/tech_logo/python.png' },
      { name: 'C-Sharp', logo: '/tech_logo/csharp.png' },
      { name: 'TypeScript', logo: '/tech_logo/typescript.png' },
    ],
  },
  {
    title: 'Công cụ',
    skills: [
      { name: 'Git', logo: '/tech_logo/git.png' },
      { name: 'GitHub', logo: '/tech_logo/github.png' },
      { name: 'VS Code', logo: '/tech_logo/vscode.png' },
      { name: 'Postman', logo: '/tech_logo/postman.png' },
      { name: 'MongoDB Compass', logo: '/tech_logo/mc.png' },
      { name: 'Vercel', logo: '/tech_logo/vercel.png' },
      { name: 'Netlify', logo: '/tech_logo/netlify.png' },
      { name: 'Figma', logo: '/tech_logo/figma.png' },
    ],
  },
  {
    title: 'Cloud & DevOps',
    skills: [
      { name: 'AWS', logo: '/tech_logo/aws.png' },
      { name: 'Docker', logo: '/tech_logo/docker.png' },
    ],
  },
  ],
  en: [
    {
      title: 'Frontend',
      skills: [
        { name: 'HTML', logo: '/tech_logo/html.png' },
        { name: 'CSS', logo: '/tech_logo/css.png' },
        { name: 'SASS', logo: '/tech_logo/sass.png' },
        { name: 'JavaScript', logo: '/tech_logo/javascript.png' },
        { name: 'React JS', logo: '/tech_logo/react.png' },
        { name: 'Redux', logo: '/tech_logo/redux.png' },
        { name: 'Next JS', logo: '/tech_logo/nextjs.png' },
        { name: 'Tailwind CSS', logo: '/tech_logo/tailwindcss.png' },
        { name: 'GSAP', logo: '/tech_logo/gsap.png' },
        { name: 'Material UI', logo: '/tech_logo/materialui.png' },
        { name: 'Bootstrap', logo: '/tech_logo/bootstrap.png' },
      ],
    },
    {
      title: 'Backend',
      skills: [
        { name: 'Springboot', logo: '/tech_logo/springboot.png' },
        { name: 'Node JS', logo: '/tech_logo/nodejs.png' },
        { name: 'Express JS', logo: '/tech_logo/express.png' },
        { name: 'Nest JS', logo: '/tech_logo/nest.png' },
        { name: 'MySQL', logo: '/tech_logo/mysql.png' },
        { name: 'MongoDB', logo: '/tech_logo/mongodb.png' },
        { name: 'PostgreSQL', logo: '/tech_logo/postgre.png' },
        { name: 'SQL', logo: '/tech_logo/sql.png' },
        { name: 'Firebase', logo: '/tech_logo/firebase.png' },
      ],
    },
    {
      title: 'Programming Languages',
      skills: [
        { name: 'C', logo: '/tech_logo/c.png' },
        { name: 'C++', logo: '/tech_logo/cpp.png' },
        { name: 'Java', logo: '/tech_logo/java.png' },
        { name: 'Python', logo: '/tech_logo/python.png' },
        { name: 'C-Sharp', logo: '/tech_logo/csharp.png' },
        { name: 'TypeScript', logo: '/tech_logo/typescript.png' },
      ],
    },
    {
      title: 'Tools',
      skills: [
        { name: 'Git', logo: '/tech_logo/git.png' },
        { name: 'GitHub', logo: '/tech_logo/github.png' },
        { name: 'VS Code', logo: '/tech_logo/vscode.png' },
        { name: 'Postman', logo: '/tech_logo/postman.png' },
        { name: 'MongoDB Compass', logo: '/tech_logo/mc.png' },
        { name: 'Vercel', logo: '/tech_logo/vercel.png' },
        { name: 'Netlify', logo: '/tech_logo/netlify.png' },
        { name: 'Figma', logo: '/tech_logo/figma.png' },
      ],
    },
    {
      title: 'Cloud & DevOps',
      skills: [
        { name: 'AWS', logo: '/tech_logo/aws.png' },
        { name: 'Docker', logo: '/tech_logo/docker.png' },
      ],
    },
  ]
};

// Dữ liệu kinh nghiệm làm việc theo ngôn ngữ
export const experiencesByLocale: Record<'vi' | 'en', ExperienceType[]> = {
  vi: [
    {
      id: 0,
      img: '/company_logo/amazon.png',
      role: "Thực tập sinh Phát triển Phần mềm",
      company: "Amazon",
      date: "06/2024 - Hiện tại",
      desc: "Thực tập sinh Phát triển Phần mềm tại Amazon, học hỏi và tham gia vào các dự án nhỏ với công nghệ hiện đại. Được hướng dẫn bởi senior developers để hiểu về dịch vụ đám mây, kiến trúc microservices và quy trình Agile trong môi trường công ty lớn.",
      skills: [
        "React",
        "TypeScript",
        "Node JS",
        "AWS",
        "Docker",
        "Git",
        "Next Js",
        "Tailwind CSS",
        "MongoDb",
        "Express",
      ],
    },
    {
      id: 1,
      img: '/company_logo/facebook.png',
      role: "Thực tập sinh Frontend",
      company: "Meta (Facebook)",
      date: "01/2024 - 05/2024",
      desc: "Hoàn thành kỳ thực tập 5 tháng tại Meta với vai trò Frontend, được hướng dẫn phát triển các thành phần giao diện đơn giản và ứng dụng web responsive. Học hỏi từ senior developer về cách xây dựng ứng dụng React và các best practice về chất lượng mã cũng như tối ưu hiệu năng.",
      skills: [
        "React",
        "Redux",
        "JavaScript",
        "TypeScript",
        "HTML",
        "CSS",
        "Material UI",
        "Figma",
      ],
    },
    {
      id: 2,
      img: '/company_logo/youtube.png',
      role: "Thực tập sinh Web",
      company: "Google (YouTube)",
      date: "09/2023 - 12/2023",
      desc: "Thực tập tại đội YouTube của Google, được hướng dẫn về phát triển frontend và cải thiện trải nghiệm người dùng. Học hỏi về công nghệ web hiện đại, thiết kế responsive và quy trình làm việc cộng tác trong môi trường công ty công nghệ lớn.",
      skills: [
        "HTML",
        "CSS",
        "JavaScript",
        "React",
        "Material UI",
        "Figma",
        "Git",
        "Bootstrap",
      ],
    },
  ],
  en: [
    {
      id: 0,
      img: '/company_logo/amazon.png',
      role: "Software Development Intern",
      company: "Amazon",
      date: "06/2024 - Present",
      desc: "Software Development Intern at Amazon, learning and contributing to small projects with modern technology. Guided by senior developers to understand cloud services, microservices architecture, and Agile processes in a large company environment.",
      skills: [
        "React",
        "TypeScript",
        "Node JS",
        "AWS",
        "Docker",
        "Git",
        "Next Js",
        "Tailwind CSS",
        "MongoDb",
        "Express",
      ],
    },
    {
      id: 1,
      img: '/company_logo/facebook.png',
      role: "Frontend Intern",
      company: "Meta (Facebook)",
      date: "01/2024 - 05/2024",
      desc: "Completed a 5-month internship at Meta as a Frontend developer, guided to develop simple UI components and responsive web applications. Learned from senior developers about building React applications and best practices for code quality and performance optimization.",
      skills: [
        "React",
        "Redux",
        "JavaScript",
        "TypeScript",
        "HTML",
        "CSS",
        "Material UI",
        "Figma",
      ],
    },
    {
      id: 2,
      img: '/company_logo/youtube.png',
      role: "Web Development Intern",
      company: "Google (YouTube)",
      date: "09/2023 - 12/2023",
      desc: "Interned at Google's YouTube team, guided in frontend development and improving user experience. Learned about modern web technologies, responsive design, and collaborative workflows in a large tech company environment.",
      skills: [
        "HTML",
        "CSS",
        "JavaScript",
        "React",
        "Material UI",
        "Figma",
        "Git",
        "Bootstrap",
      ],
    },
  ]
};
  